
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  vuln_app:
    depends_on:
      - db
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/hello_web_dev
      - SECRET_KEY_BASE=27Swe6KtEtmN37WyEYRjKWyxYULNtrxlkCEKur4qoV+Lwtk8lafsR16ifz1XBBYj
    command: bash -c "/app/bin/hello_web eval \"HelloWeb.Release.create_and_migrate()\" && /app/bin/hello_web start"

    